# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Sep  6 23:11:42 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1263, 781)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.experimentIDLineEdit = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setItalic(True)
        self.experimentIDLineEdit.setFont(font)
        self.experimentIDLineEdit.setObjectName(_fromUtf8("experimentIDLineEdit"))
        self.verticalLayout_4.addWidget(self.experimentIDLineEdit)
        self.experimentdescriptionTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experimentdescriptionTextEdit.sizePolicy().hasHeightForWidth())
        self.experimentdescriptionTextEdit.setSizePolicy(sizePolicy)
        self.experimentdescriptionTextEdit.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setItalic(True)
        self.experimentdescriptionTextEdit.setFont(font)
        self.experimentdescriptionTextEdit.setObjectName(_fromUtf8("experimentdescriptionTextEdit"))
        self.verticalLayout_4.addWidget(self.experimentdescriptionTextEdit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.stackView = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackView.sizePolicy().hasHeightForWidth())
        self.stackView.setSizePolicy(sizePolicy)
        self.stackView.setMinimumSize(QtCore.QSize(200, 200))
        self.stackView.setObjectName(_fromUtf8("stackView"))
        self.verticalLayout_4.addWidget(self.stackView)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.binsizeLabel = QtGui.QLabel(self.centralwidget)
        self.binsizeLabel.setObjectName(_fromUtf8("binsizeLabel"))
        self.horizontalLayout_5.addWidget(self.binsizeLabel)
        self.binsizeSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.binsizeSpinBox.setObjectName(_fromUtf8("binsizeSpinBox"))
        self.horizontalLayout_5.addWidget(self.binsizeSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.spectrumviewLabel = QtGui.QLabel(self.centralwidget)
        self.spectrumviewLabel.setObjectName(_fromUtf8("spectrumviewLabel"))
        self.verticalLayout_2.addWidget(self.spectrumviewLabel)
        self.allhitsRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.allhitsRadioButton.setObjectName(_fromUtf8("allhitsRadioButton"))
        self.verticalLayout_2.addWidget(self.allhitsRadioButton)
        self.singlehitsRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.singlehitsRadioButton.setEnabled(False)
        self.singlehitsRadioButton.setObjectName(_fromUtf8("singlehitsRadioButton"))
        self.verticalLayout_2.addWidget(self.singlehitsRadioButton)
        self.multiplehitsRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.multiplehitsRadioButton.setEnabled(False)
        self.multiplehitsRadioButton.setObjectName(_fromUtf8("multiplehitsRadioButton"))
        self.verticalLayout_2.addWidget(self.multiplehitsRadioButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.minhitsLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.minhitsLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minhitsLineEdit.sizePolicy().hasHeightForWidth())
        self.minhitsLineEdit.setSizePolicy(sizePolicy)
        self.minhitsLineEdit.setMinimumSize(QtCore.QSize(75, 0))
        self.minhitsLineEdit.setBaseSize(QtCore.QSize(75, 0))
        self.minhitsLineEdit.setMaxLength(3)
        self.minhitsLineEdit.setObjectName(_fromUtf8("minhitsLineEdit"))
        self.horizontalLayout_2.addWidget(self.minhitsLineEdit)
        self.maxhitsLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.maxhitsLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxhitsLineEdit.sizePolicy().hasHeightForWidth())
        self.maxhitsLineEdit.setSizePolicy(sizePolicy)
        self.maxhitsLineEdit.setMinimumSize(QtCore.QSize(75, 10))
        self.maxhitsLineEdit.setBaseSize(QtCore.QSize(75, 10))
        self.maxhitsLineEdit.setMaxLength(3)
        self.maxhitsLineEdit.setObjectName(_fromUtf8("maxhitsLineEdit"))
        self.horizontalLayout_2.addWidget(self.maxhitsLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.plotsLayout = QtGui.QVBoxLayout()
        self.plotsLayout.setObjectName(_fromUtf8("plotsLayout"))
        self.rangedLayout = QtGui.QVBoxLayout()
        self.rangedLayout.setObjectName(_fromUtf8("rangedLayout"))
        self.ranged_Label = QtGui.QLabel(self.centralwidget)
        self.ranged_Label.setObjectName(_fromUtf8("ranged_Label"))
        self.rangedLayout.addWidget(self.ranged_Label)
        self.rangedFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangedFrame.sizePolicy().hasHeightForWidth())
        self.rangedFrame.setSizePolicy(sizePolicy)
        self.rangedFrame.setMinimumSize(QtCore.QSize(550, 300))
        self.rangedFrame.setObjectName(_fromUtf8("rangedFrame"))
        self.rangedLayout.addWidget(self.rangedFrame)
        self.plotsLayout.addLayout(self.rangedLayout)
        self.workingLayout = QtGui.QVBoxLayout()
        self.workingLayout.setObjectName(_fromUtf8("workingLayout"))
        self.working_Label = QtGui.QLabel(self.centralwidget)
        self.working_Label.setObjectName(_fromUtf8("working_Label"))
        self.workingLayout.addWidget(self.working_Label)
        self.workingFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workingFrame.sizePolicy().hasHeightForWidth())
        self.workingFrame.setSizePolicy(sizePolicy)
        self.workingFrame.setMinimumSize(QtCore.QSize(550, 350))
        self.workingFrame.setObjectName(_fromUtf8("workingFrame"))
        self.workingLayout.addWidget(self.workingFrame)
        self.plotsLayout.addLayout(self.workingLayout)
        self.horizontalLayout.addLayout(self.plotsLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rangedTable = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangedTable.sizePolicy().hasHeightForWidth())
        self.rangedTable.setSizePolicy(sizePolicy)
        self.rangedTable.setMinimumSize(QtCore.QSize(100, 335))
        self.rangedTable.setFrameShadow(QtGui.QFrame.Sunken)
        self.rangedTable.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.rangedTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.rangedTable.setGridStyle(QtCore.Qt.SolidLine)
        self.rangedTable.setSortingEnabled(True)
        self.rangedTable.setObjectName(_fromUtf8("rangedTable"))
        self.rangedTable.horizontalHeader().setDefaultSectionSize(65)
        self.rangedTable.horizontalHeader().setMinimumSectionSize(20)
        self.rangedTable.horizontalHeader().setStretchLastSection(True)
        self.rangedTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.rangedTable)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.commitButton = QtGui.QPushButton(self.centralwidget)
        self.commitButton.setObjectName(_fromUtf8("commitButton"))
        self.horizontalLayout_6.addWidget(self.commitButton)
        self.deleteButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_6.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.tab_Tab = QtGui.QTabWidget(self.centralwidget)
        self.tab_Tab.setObjectName(_fromUtf8("tab_Tab"))
        self.peakID_Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peakID_Tab.sizePolicy().hasHeightForWidth())
        self.peakID_Tab.setSizePolicy(sizePolicy)
        self.peakID_Tab.setObjectName(_fromUtf8("peakID_Tab"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.peakID_Tab)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ionlistTree = QtGui.QTreeView(self.peakID_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ionlistTree.sizePolicy().hasHeightForWidth())
        self.ionlistTree.setSizePolicy(sizePolicy)
        self.ionlistTree.setMinimumSize(QtCore.QSize(50, 100))
        self.ionlistTree.setDragEnabled(True)
        self.ionlistTree.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.ionlistTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ionlistTree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.ionlistTree.setSortingEnabled(True)
        self.ionlistTree.setObjectName(_fromUtf8("ionlistTree"))
        self.horizontalLayout_7.addWidget(self.ionlistTree)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.knownelementsLabel = QtGui.QLabel(self.peakID_Tab)
        self.knownelementsLabel.setObjectName(_fromUtf8("knownelementsLabel"))
        self.verticalLayout_9.addWidget(self.knownelementsLabel)
        self.knownelementsLineEdit = QtGui.QLineEdit(self.peakID_Tab)
        self.knownelementsLineEdit.setMaximumSize(QtCore.QSize(16577215, 16777215))
        self.knownelementsLineEdit.setText(_fromUtf8(""))
        self.knownelementsLineEdit.setObjectName(_fromUtf8("knownelementsLineEdit"))
        self.verticalLayout_9.addWidget(self.knownelementsLineEdit)
        self.maxchargestateLabel = QtGui.QLabel(self.peakID_Tab)
        self.maxchargestateLabel.setObjectName(_fromUtf8("maxchargestateLabel"))
        self.verticalLayout_9.addWidget(self.maxchargestateLabel)
        self.maxchargestateLineEdit = QtGui.QLineEdit(self.peakID_Tab)
        self.maxchargestateLineEdit.setObjectName(_fromUtf8("maxchargestateLineEdit"))
        self.verticalLayout_9.addWidget(self.maxchargestateLineEdit)
        self.suggestButton = QtGui.QPushButton(self.peakID_Tab)
        self.suggestButton.setEnabled(False)
        self.suggestButton.setDefault(True)
        self.suggestButton.setObjectName(_fromUtf8("suggestButton"))
        self.verticalLayout_9.addWidget(self.suggestButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.addionsButton = QtGui.QPushButton(self.peakID_Tab)
        self.addionsButton.setEnabled(False)
        self.addionsButton.setDefault(True)
        self.addionsButton.setObjectName(_fromUtf8("addionsButton"))
        self.verticalLayout_6.addWidget(self.addionsButton)
        self.removeionsButton = QtGui.QPushButton(self.peakID_Tab)
        self.removeionsButton.setEnabled(False)
        self.removeionsButton.setObjectName(_fromUtf8("removeionsButton"))
        self.verticalLayout_6.addWidget(self.removeionsButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.tab_Tab.addTab(self.peakID_Tab, _fromUtf8(""))
        self.composition_Tab = QtGui.QWidget()
        self.composition_Tab.setObjectName(_fromUtf8("composition_Tab"))
        self.tab_Tab.addTab(self.composition_Tab, _fromUtf8(""))
        self.advanced_Tab = QtGui.QWidget()
        self.advanced_Tab.setObjectName(_fromUtf8("advanced_Tab"))
        self.tab_Tab.addTab(self.advanced_Tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_Tab)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1263, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuLoad = QtGui.QMenu(self.menuEdit)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menuExport_as = QtGui.QMenu(self.menuEdit)
        self.menuExport_as.setObjectName(_fromUtf8("menuExport_as"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen_Recent = QtGui.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName(_fromUtf8("actionOpen_Recent"))
        self.actionLoad = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../.designer/backup/document_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionHistory = QtGui.QAction(MainWindow)
        self.actionHistory.setObjectName(_fromUtf8("actionHistory"))
        self.actionAs_rng = QtGui.QAction(MainWindow)
        self.actionAs_rng.setObjectName(_fromUtf8("actionAs_rng"))
        self.actionAs_mr = QtGui.QAction(MainWindow)
        self.actionAs_mr.setObjectName(_fromUtf8("actionAs_mr"))
        self.actionLoad_rng = QtGui.QAction(MainWindow)
        self.actionLoad_rng.setObjectName(_fromUtf8("actionLoad_rng"))
        self.actionLoad_mr = QtGui.QAction(MainWindow)
        self.actionLoad_mr.setObjectName(_fromUtf8("actionLoad_mr"))
        self.action_LoadRNG = QtGui.QAction(MainWindow)
        self.action_LoadRNG.setObjectName(_fromUtf8("action_LoadRNG"))
        self.action_LoadMR = QtGui.QAction(MainWindow)
        self.action_LoadMR.setObjectName(_fromUtf8("action_LoadMR"))
        self.action_ExportAsRNG = QtGui.QAction(MainWindow)
        self.action_ExportAsRNG.setObjectName(_fromUtf8("action_ExportAsRNG"))
        self.action_ExportAsMR = QtGui.QAction(MainWindow)
        self.action_ExportAsMR.setObjectName(_fromUtf8("action_ExportAsMR"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuHelp.addAction(self.actionAbout)
        self.menuLoad.addAction(self.action_LoadRNG)
        self.menuLoad.addAction(self.action_LoadMR)
        self.menuExport_as.addAction(self.action_ExportAsRNG)
        self.menuExport_as.addAction(self.action_ExportAsMR)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuLoad.menuAction())
        self.menuEdit.addAction(self.menuExport_as.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.experimentIDLineEdit.setText(_translate("MainWindow", "Experiment ID", None))
        self.experimentdescriptionTextEdit.setPlainText(_translate("MainWindow", "Description...", None))
        self.binsizeLabel.setText(_translate("MainWindow", "Bin size", None))
        self.spectrumviewLabel.setText(_translate("MainWindow", "Spectrum View", None))
        self.allhitsRadioButton.setText(_translate("MainWindow", "All hits", None))
        self.singlehitsRadioButton.setText(_translate("MainWindow", "Single hits", None))
        self.multiplehitsRadioButton.setText(_translate("MainWindow", "Multiple hits", None))
        self.minhitsLineEdit.setText(_translate("MainWindow", "Min", None))
        self.maxhitsLineEdit.setText(_translate("MainWindow", "Max", None))
        self.ranged_Label.setText(_translate("MainWindow", "Ranged", None))
        self.working_Label.setText(_translate("MainWindow", "Working", None))
        self.commitButton.setText(_translate("MainWindow", "Commit", None))
        self.deleteButton.setText(_translate("MainWindow", "Delete", None))
        self.deleteButton.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.knownelementsLabel.setText(_translate("MainWindow", "Known elements", None))
        self.maxchargestateLabel.setText(_translate("MainWindow", "Max charge state", None))
        self.suggestButton.setText(_translate("MainWindow", "Suggest", None))
        self.addionsButton.setText(_translate("MainWindow", "Add", None))
        self.removeionsButton.setText(_translate("MainWindow", "Remove", None))
        self.tab_Tab.setTabText(self.tab_Tab.indexOf(self.peakID_Tab), _translate("MainWindow", "Peak ID", None))
        self.tab_Tab.setTabText(self.tab_Tab.indexOf(self.composition_Tab), _translate("MainWindow", "Composition", None))
        self.tab_Tab.setTabText(self.tab_Tab.indexOf(self.advanced_Tab), _translate("MainWindow", "Advanced", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuLoad.setTitle(_translate("MainWindow", "Load...", None))
        self.menuExport_as.setTitle(_translate("MainWindow", "Export as...", None))
        self.actionNew.setText(_translate("MainWindow", "New...", None))
        self.actionNew.setToolTip(_translate("MainWindow", "Click to create a new project", None))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new project", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpen.setText(_translate("MainWindow", "Open...", None))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent", None))
        self.actionLoad.setText(_translate("MainWindow", "Load data...", None))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As...", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z", None))
        self.actionHistory.setText(_translate("MainWindow", "History", None))
        self.actionAs_rng.setText(_translate("MainWindow", "as .rng", None))
        self.actionAs_mr.setText(_translate("MainWindow", "as .mr", None))
        self.actionLoad_rng.setText(_translate("MainWindow", "Load .rng", None))
        self.actionLoad_mr.setText(_translate("MainWindow", "Load .mr", None))
        self.action_LoadRNG.setText(_translate("MainWindow", ".rng", None))
        self.action_LoadMR.setText(_translate("MainWindow", ".mr", None))
        self.action_ExportAsRNG.setText(_translate("MainWindow", ".rng", None))
        self.action_ExportAsMR.setText(_translate("MainWindow", ".mr", None))

