# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools.ui'
#
# Created: Tue Sep 22 19:13:17 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ToolsDialog(object):
    def setupUi(self, ToolsDialog):
        ToolsDialog.setObjectName(_fromUtf8("ToolsDialog"))
        ToolsDialog.resize(444, 307)
        self.verticalLayout = QtGui.QVBoxLayout(ToolsDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tab_Tab = QtGui.QTabWidget(ToolsDialog)
        self.tab_Tab.setObjectName(_fromUtf8("tab_Tab"))
        self.peakID_Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peakID_Tab.sizePolicy().hasHeightForWidth())
        self.peakID_Tab.setSizePolicy(sizePolicy)
        self.peakID_Tab.setObjectName(_fromUtf8("peakID_Tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.peakID_Tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ionlistTree = QtGui.QTreeView(self.peakID_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ionlistTree.sizePolicy().hasHeightForWidth())
        self.ionlistTree.setSizePolicy(sizePolicy)
        self.ionlistTree.setMinimumSize(QtCore.QSize(200, 100))
        self.ionlistTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ionlistTree.setDragEnabled(True)
        self.ionlistTree.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.ionlistTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ionlistTree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.ionlistTree.setSortingEnabled(True)
        self.ionlistTree.setObjectName(_fromUtf8("ionlistTree"))
        self.horizontalLayout_2.addWidget(self.ionlistTree)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.knownelementsLabel = QtGui.QLabel(self.peakID_Tab)
        self.knownelementsLabel.setObjectName(_fromUtf8("knownelementsLabel"))
        self.verticalLayout_2.addWidget(self.knownelementsLabel)
        self.knownelementsLineEdit = QtGui.QLineEdit(self.peakID_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.knownelementsLineEdit.sizePolicy().hasHeightForWidth())
        self.knownelementsLineEdit.setSizePolicy(sizePolicy)
        self.knownelementsLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.knownelementsLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.knownelementsLineEdit.setText(_fromUtf8(""))
        self.knownelementsLineEdit.setObjectName(_fromUtf8("knownelementsLineEdit"))
        self.verticalLayout_2.addWidget(self.knownelementsLineEdit)
        self.maxchargestateLabel = QtGui.QLabel(self.peakID_Tab)
        self.maxchargestateLabel.setObjectName(_fromUtf8("maxchargestateLabel"))
        self.verticalLayout_2.addWidget(self.maxchargestateLabel)
        self.maxchargestateLineEdit = QtGui.QLineEdit(self.peakID_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxchargestateLineEdit.sizePolicy().hasHeightForWidth())
        self.maxchargestateLineEdit.setSizePolicy(sizePolicy)
        self.maxchargestateLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.maxchargestateLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.maxchargestateLineEdit.setObjectName(_fromUtf8("maxchargestateLineEdit"))
        self.verticalLayout_2.addWidget(self.maxchargestateLineEdit)
        self.suggestButton = QtGui.QPushButton(self.peakID_Tab)
        self.suggestButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suggestButton.sizePolicy().hasHeightForWidth())
        self.suggestButton.setSizePolicy(sizePolicy)
        self.suggestButton.setMinimumSize(QtCore.QSize(160, 0))
        self.suggestButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.suggestButton.setDefault(True)
        self.suggestButton.setObjectName(_fromUtf8("suggestButton"))
        self.verticalLayout_2.addWidget(self.suggestButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.addionsButton = QtGui.QPushButton(self.peakID_Tab)
        self.addionsButton.setEnabled(False)
        self.addionsButton.setDefault(True)
        self.addionsButton.setObjectName(_fromUtf8("addionsButton"))
        self.verticalLayout_6.addWidget(self.addionsButton)
        self.clearionsButton = QtGui.QPushButton(self.peakID_Tab)
        self.clearionsButton.setEnabled(False)
        self.clearionsButton.setObjectName(_fromUtf8("clearionsButton"))
        self.verticalLayout_6.addWidget(self.clearionsButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.tab_Tab.addTab(self.peakID_Tab, _fromUtf8(""))
        self.composition_Tab = QtGui.QWidget()
        self.composition_Tab.setObjectName(_fromUtf8("composition_Tab"))
        self.tab_Tab.addTab(self.composition_Tab, _fromUtf8(""))
        self.history_Tab = QtGui.QWidget()
        self.history_Tab.setObjectName(_fromUtf8("history_Tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.history_Tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.stackView = QtGui.QWidget(self.history_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackView.sizePolicy().hasHeightForWidth())
        self.stackView.setSizePolicy(sizePolicy)
        self.stackView.setMinimumSize(QtCore.QSize(200, 200))
        self.stackView.setObjectName(_fromUtf8("stackView"))
        self.verticalLayout_3.addWidget(self.stackView)
        self.tab_Tab.addTab(self.history_Tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_Tab)

        self.retranslateUi(ToolsDialog)
        self.tab_Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ToolsDialog)

    def retranslateUi(self, ToolsDialog):
        ToolsDialog.setWindowTitle(_translate("ToolsDialog", "Dialog", None))
        self.knownelementsLabel.setText(_translate("ToolsDialog", "Known elements", None))
        self.maxchargestateLabel.setText(_translate("ToolsDialog", "Max charge state", None))
        self.suggestButton.setText(_translate("ToolsDialog", "Suggest", None))
        self.addionsButton.setText(_translate("ToolsDialog", "Add", None))
        self.clearionsButton.setText(_translate("ToolsDialog", "Clear", None))
        self.tab_Tab.setTabText(self.tab_Tab.indexOf(self.peakID_Tab), _translate("ToolsDialog", "Peak ID", None))
        self.tab_Tab.setTabText(self.tab_Tab.indexOf(self.composition_Tab), _translate("ToolsDialog", "Composition", None))
        self.tab_Tab.setTabText(self.tab_Tab.indexOf(self.history_Tab), _translate("ToolsDialog", "History", None))

